### ISSUE TITLE
Undefined behaviour sanitizer errors

### ISSUE THREAD

**Issue by DaanDeMeyer** [ned14/status-code#12]
UBSan is giving me warnings from some system_error2 stuff.

https://travis-ci.com/DaanDeMeyer/bnl/jobs/218341783  (scroll down to end)

Here's one of the error domains UBSan complains about:

https://github.com/DaanDeMeyer/bnl/blob/master/bnl/base/include/bnl/http3/error.hpp

Do you think this is a false positive or am I using system_error2 wrong in some way?

The weird thing is I'm not getting these UBSan errors locally (Arch Linux system, latest everything) which makes me think it might be a bug somewhere in UBSan although I'm using clang 8 here as well which is the same as on my local system.

**Comment by ned14** [comment]
Boost.Outcome *was* failing ubsan on older clang versions when using status code, but recently it has become fixed.

If it is the same point of failure, I did investigate and I concluded it is a bug in ubsan.
