### ISSUE TITLE
Fundamental flaw of this library. Without an operating system, this will not work.

### ISSUE THREAD

**Issue by euloanty** [ned14/status-code#13]
It needs malloc which requires an OS. Then people can never use C++ to write OS since there is no malloc.

A lot of embedded systems might not have an OS as well.

Please consider a method to make it header only. No DLL. No linking please.

**Comment by ned14** [comment]
`malloc()` is never called unless a status code pointer is manufactured, or a string representation of a POSIX error code is retrieved.

status-code has already been deployed onto many embedded systems, including fully freestanding ones, without issue.

The library already provides a build option for header only. Boost.Outcome uses the header only edition.

**Comment by euloanty** [comment]
@ned14 But you are designing the prototype of std::error. I do not know whether it requires linking or something to make it work. Considering nt_error_category requires dll which destroyed my project.

**Comment by euloanty** [comment]
The library already provides a build option for header only.
I do not want any build option. It will destroy everything.

**Comment by euloanty** [comment]
> `malloc()` is never called unless a status code pointer is manufactured, or a string representation of a POSIX error code is retrieved.
> 
> status-code has already been deployed onto many embedded systems, including fully freestanding ones, without issue.
> 
> The library already provides a build option for header only. Boost.Outcome uses the header only edition.

string_ref/atomic_string_ref are problems. People hate it.

**Comment by euloanty** [comment]
Also, I do not know what is your solution to the interface bloating issue. Here is an example of get char from stream. Because of EOF, the interface has to provide two get(). One is get() which throws exceptions when it reaches EOF, the other is try_get(), which will return <char,bool> when the stream reaches EOF. Then use this interface to implement read unsigned integers. throws std::error is an overhead.

template<std::uint8_t base,standard_input_stream input,std::integral U>
inline constexpr void input_base_number_phase2(input& in,U& a)
{
	using unsigned_char_type = std::make_unsigned_t<decltype(in.get())>;
	unsigned_char_type constexpr baseed(std::min(static_cast<unsigned_char_type>(base),static_cast<unsigned_char_type>(10)));
	while(true)
	{
		unsigned_char_type ch(in.try_get().first);
		if((ch-=48)<baseed)
			a=a*base+ch;
		else if constexpr (10 < base)
		{
			unsigned_char_type constexpr bm10(base-10);
			if((ch-=17)<bm10||(ch-=32)<bm10)
				a=a*base+(ch+10);
			else
				return;
		}
		else
			return;
	}
}

template<std::uint8_t base,standard_input_stream input,std::unsigned_integral U>
inline constexpr void input_base_number(input& in,U& a)
{
	using unsigned_char_type = std::make_unsigned_t<decltype(in.get())>;
	unsigned_char_type constexpr baseed(std::min(static_cast<unsigned_char_type>(base),static_cast<unsigned_char_type>(10)));
	while(true)
	{
		unsigned_char_type ch(in.get());
		if((ch-=48)<baseed)
		{
			a=ch;
			break;
		}
		else if constexpr (10 < base)
		{
			unsigned_char_type constexpr bm10(base-10);
			if((ch-=17)<bm10||(ch-=32)<bm10)
				a=a*base+ch+10;
			{
				a=ch+10;
				break;
			}
		}
	}
	input_base_number_phase2<base>(in,a);
}
