### ISSUE TITLE
Newest MSVC can't compile avoid_stdio_include::write

### ISSUE THREAD

**Issue by interj** [ned14/status-code#17]
Apparently new MSVC (19.23 or 14.23 or whatever out-of-whack version there is) hates `extern "C" write` too.
https://github.com/ned14/status-code/blob/a1b58e60877ca450cef8349eac07de4ac266f12e/include/config.hpp#L283
Dropping C linkage from signature solves the issue, but I don't know if it won't break something else, since this is a POSIX function. Also, write is deprecated in Windows CRT, so this might break yet again in the future.

**Comment by ned14** [comment]
I updated the single header include which was stale, sorry.

I'm on MSVC 19.23.28107 and not seeing any issue with what you mention above. Can you try trunk?

**Comment by interj** [comment]
I don't think this is related - this particular problem originated in outcome-experimental header and these changes where already present in https://github.com/ned14/outcome/commit/8a8431ee03a871f2f9c29fa09a0a95185cf4bc1d

**Comment by gix** [comment]
There are several problems with that declaration. First, Microsoft's UCRT only has a 32-bit version (`int write(int, const void *, unsigned)` so the compiler complains about mismatched parameter types. Second, the missing `__declspec(dllimport)` results in a redeclaration compilation error when it encounters the real declaration when linking against a dynamic runtime. But adding it prevents linking the runtime statically. This could be solved using the same `/alternatename` workaround as elsewhere.

**Comment by ned14** [comment]
Lets try the usual MSVC linker hack then. Thanks for the suggestion.
