### ISSUE TITLE
Additional move-constructor call in status_code.message()

### ISSUE THREAD

**Issue by Tradias** [ned14/status-code#30]
In MSVC the ternary operator in status_code.hpp:445

```
  string_ref message() const noexcept { return this->_domain ? string_ref(this->domain()._do_message(*this)) : string_ref("(empty)"); 
```
causes an additional call to the move-constructor (and therefore destructor) of `string_ref`. See https://godbolt.org/z/1vW4WY

**Comment by ned14** [comment]
Thanks for the bug report!
