### ISSUE TITLE
status_code.hpp vs. system_error2.hpp

### ISSUE THREAD

**Issue by qknight** [ned14/status-code#33]
In our examples we are using system_error2.hpp but what is the status_code.hpp used for?

Or in other words, the standard is planned to be called 'status code' so isn't status_code.hpp eventually the header one would include and use as a basis?

**Comment by ned14** [comment]
LEWG haven't thought about header naming nor inclusion segmentation for this feature yet. Still on bikeshedding the class names.

I roughly follow a header per category of classes. You should be able to include what you need and nothing extra if you wish.
