### ISSUE TITLE
This status code completely violates freestanding requirement.

### ISSUE THREAD

**Issue by tearosccebe** [ned14/status-code#40]
1. cassert, cstring, utility etc headers are NOT freestanding. You cannot use them.

https://en.cppreference.com/w/cpp/freestanding

[std::move](https://github.com/ned14/status-code/blob/85ab0c13edc8fbfa7182cfb2b947b5e40ff24aa5/include/result.hpp#L151)

std::move, std::forward, std::addressof, std::array etc are not available in freestanding either. You cannot use them.

2.  Heap allocation is HIGHLY likely to be unavailable. string_ref adds burden to implementation and binary bloat.
3. virtual functions introduce __cxa_pure_virtual() that is NOT defined in freestanding either.

I think the idea of P0709 is fine but this status code is completely useless. I am sorry to say that.

https://www.youtube.com/watch?v=DorYSHu4Sjk

**Comment by ned14** [comment]
Thanks for your note.

As a WG21 destined reference implementation library. this library targets a future Freestanding, not current Freestanding. The WG21 leads for Freestanding have looked over this library, and found no theoretical problem with anything done here wrt to standardisation.

There are plenty of folk who have deployed this library onto some very limited toolchains with success. If any patchsets fixing build issues on a reasonable modern common embedded target arrives here, I will consider it.
