### ISSUE TITLE
UAF error (probably?) with thrown_exception_domain example when exceptions contain dynamic strings

### ISSUE THREAD

**Issue by MHebes** [ned14/status-code#56]
I was trying to use https://github.com/ned14/status-code/blob/master/example/thrown_exception.cpp to help migrate an existing codebase that sometimes uses exceptions. It's failing for cases where the exception itself owns the storage of it's `what()` string:

```c++
#include "exception_ptr_domain.h"

void throw_something() { throw std::logic_error("oops"); }

int main() {
  try {
    throw_something();
  } catch (std::exception& e) {
    printf("Exception has message %s\n", e.what());
    auto eptr = std::current_exception();
    thrown_exception_code tec = make_status_code(eptr);
    system_code sc(tec);
    printf("Thrown exception code has message %s\n", sc.message().c_str());
    printf("Thrown exception code == errc::not_enough_memory = %d\n",
           sc == errc::not_enough_memory);
  }
  return 0;
}
```

This is giving garbage out:

```text
Exception has message oops
Thrown exception code has message ▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌Cû_▌
Thrown exception code == errc::not_enough_memory = 0
```

I'm on latest MSVC with C++20. It actually looks like it's getting the right exception and everything:

![image](https://github.com/ned14/status-code/assets/8306042/b7797a11-6f00-446a-aaf1-a1b523724933)

But it seems the exception is destroyed by the time `_thrown_exception_domain::_do_message` returns:

![image](https://github.com/ned14/status-code/assets/8306042/f3382055-2382-49c5-81fa-3b61c37363f7)

Any idea what's going on here? I get the same result with `std::make_exception_ptr`, if that helps.

**Comment by ned14** [comment]
If the C++ exception type is `std::runtime_error`, does that work okay?

**Comment by MHebes** [comment]
> If the C++ exception type is `std::runtime_error`, does that work okay?

No, if I `throw std::runtime_error("oops")` instead, I get the same issue. A custom exception also produces the issue:

```c++
class MyException : public std::exception {
  std::string owned_string_;

 public:
  MyException(std::string str) : owned_string_(std::move(str)) {}
  [[nodiscard]] const char* what() const override {
    return owned_string_.c_str();
  }
};

void throw_something() { throw MyException("oops"); }

// ...
```

```text
Exception has message oops
Thrown exception code has message ê|╔┘°
Thrown exception code == errc::not_enough_memory = 0
```

**Comment by ned14** [comment]
I added your repro to the test suite. I cannot repro it on Linux with GCC nor on Windows with MSVC. Address sanitiser is clean on both.

You sure you're on latest status-code and not an older version? There were bug fixes here in the recent past.

**Comment by BurningEnlightenment** [comment]
I have updated the test to reliably reproduce the issue on MSVC 19.36.32537.0 (note that the CI doesn't run the test executable):
```
Exception has message oops
strcmp(msg.c_str(), "oops") == 0 failed at line 67
Thrown exception code has message `Xü¡Î
```

**Comment by MHebes** [comment]
> I think this is a side effect of [P1675](https://wg21.link/P1675): `std::rethrow_exception` is allowed to create a temporary copy of the exception object and throw that instead of the original object.

I think you're right. If I add `printf`s like Herb Stutter does in that:

```c++
// main.cpp
// ...
int main() {
  try {
    throw_something();
  } catch (std::exception& e) {
    printf("main() caught with address %llu\n", (void*)&e);
// ...

// exception_ptr_domain.h
// ...
  virtual _base::string_ref _do_message(
      const status_code<void>& code) const noexcept override final {
// ...
    } catch (const std::exception& x) {
      printf("_do_message() caught with address %llu\n", (void*)&x);
      return _base::string_ref(x.what());
// ...
```

The exception objects have different addresses:

```text
main() caught with address 583730722496
Exception has message oops
_do_message() caught with address 583730712576
Thrown exception code has message ▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌+TáÅ▌$
Thrown exception code == errc::not_enough_memory = 0
```

Testing reveals that their `what` strings have different addresses as well.

**Comment by BurningEnlightenment** [comment]
> sptr = std::make_shared<std::exception>(e);
That's going to slice the exception object which will neither preserve the vtable nor the exception message (you can nicely observe this in [this example](https://godbolt.org/z/qEWev14MP)). It still drives me nuts that `std::exception` has a public copy constructor and a public copy assignment operator.

**Comment by MHebes** [comment]
> > `sptr = std::make_shared<std::exception>(e);`
> 
> That's going to slice the exception object which will neither preserve the vtable nor the exception message (you can nicely observe this in [this example](https://godbolt.org/z/qEWev14MP)). It still drives me nuts that `std::exception` has a public copy constructor and a public copy assignment operator.

You're right. Darn. I guess that's the problem `exception_ptr` was supposed to solve in the first place. Not sure how to solve this then.

I guess as a reduced-functionality version I could save a `atomic_refcounted_string_ref` of the what-string in the global storage instead of the whole object.

**Comment by MHebes** [comment]
Wait, I think I've confused myself—why would the what-strings have different addresses in the first place? The `logic_error` points to a static lifetime char array. Even if `current_exception` and `rethrow_exception` are copying the exception object, surely they'd all be pointing to the same part of the .data section?

**Comment by ned14** [comment]
I still need to test @BurningEnlightenment 's repro which actually repros. Chances are it'll be next week. But _surely_ this is solvable, I cannot believe that `std::exception_ptr` drops the storage backing `what()` in a production compiler.

**Comment by MHebes** [comment]
No rush of course. Also for what it's worth, on my machine, it is behaving correctly in release mode (possibly accidentally?).

```text
$ ./bin/Release/test-issue0056.exe
Exception has message oops
Thrown exception code has message oops

$ ./bin/Debug/test-issue0056.exe
Exception has message oops
strcmp(msg.c_str(), "oops") == 0 failed at line 67
Thrown exception code has message ▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌R■Q6▌$
```

**Comment by BurningEnlightenment** [comment]
> Probably a fluke that it worked in release mode.

FYA the release builds of my uploaded repro don't trigger the issue until you run it with a debugger attached. Guess I found a way to sniff out whether running under a debugger or not 😁

**Comment by ned14** [comment]
Yep so the issue was MSVC makes fresh new copies of exception ptrs every time you rethrow them, and of course the string returned then vanishes as soon as the try block exits. Fixed by having the example copy the string on Windows only. Let me know if this fixes the problem for you.

**Comment by MHebes** [comment]
> Yep so the issue was MSVC makes fresh new copies of exception ptrs every time you rethrow them, and of course the string returned then vanishes as soon as the try block exits. Fixed by having the example copy the string on Windows only. Let me know if this fixes the problem for you.

Seems to work great. Thanks for the fix!

**Comment by ned14** [comment]
Thanks for the BR!
