### ISSUE TITLE
Friend declaration of `indirecting_domain` & nested_status_code/status_code_ptr in single header version

### ISSUE THREAD

**Issue by cstratopoulos** [ned14/status-code#58]
Hi again!

I was trying to follow the docs from https://ned14.github.io/outcome/experimental/worked-example/implicit_conversion/ to create a status code with a `value_type` bigger than an `intptr_t`. A couple things

1. Very possibly I'm missing something, but it seems that using `make_nested_status_code` (or `make_status_code_ptr` in the old version) requires a `friend` declaration for `detail::indirecting_status_domain`--maybe this should be documented?

2. I believe the `friend` declaration may be misspelled in the abstract base class here? There is no `detail::` namespace as there is for `posix_code`, `generic_code`, etc. https://github.com/ned14/status-code/blob/6bd2d565fd4377e16614c6c5beb495c33bfa835b/include/status-code/status_code_domain.hpp#L107 
https://github.com/ned14/status-code/blob/6bd2d565fd4377e16614c6c5beb495c33bfa835b/include/status-code/posix_code.hpp#L78
4. This just came up incidentally when trying to isolate my compile error on godbolt, but it looks like the single header version does not include the `indirecting_domain` stuff. I notice that the single-header readme still refers to `status_code_ptr.hpp`, but there is no mention of `make_status_code_ptr` or `make_nested_status_code` in any of the generated headers. 

All the best

**Comment by ned14** [comment]
I fixed the other two. Can you explain more this one?

> Very possibly I'm missing something, but it seems that using make_nested_status_code (or make_status_code_ptr in the old version) requires a friend declaration for detail::indirecting_status_domain--maybe this should be documented?

**Comment by cstratopoulos** [comment]
Cool! And yeah regarding the first one, let's say we have `class MyDomain` and `using MyCode = status_code<MyDomain>`. Then `indirecting_domain<MyCode, Alloc>` was giving me the error 
> MyDomain::_do_throw_exception: cannot access protected member declared in class MyDomain

I think this is because most of the `protected` members just indirect to the underlying domain type, e.g., 
https://github.com/ned14/status-code/blob/6bd2d565fd4377e16614c6c5beb495c33bfa835b/include/status-code/nested_status_code.hpp#L99

But `_do_failure` is in all likelihood protected in the domain being indirected, and `indirecting_domain` has no inheritance relationship to that domain, so it doesn't work.

**Comment by BurningEnlightenment** [comment]
Well, `status_code_domain` already befriends `indirecting_domain` here:
https://github.com/ned14/status-code/blob/2086dafa6c26a50ddca0e1ecde56a7fb6728b486/include/status-code/status_code_domain.hpp#L104-L107

I.e. we can remove the need for friend declarations in every domain type by upcasting to `status_code_domain` like so:
```patch
diff --git a/include/status-code/nested_status_code.hpp b/include/status-code/nested_status_code.hpp
--- include/status-code/nested_status_code.hpp
+++ include/status-code/nested_status_code.hpp
@@ -101,9 +101,10 @@
     virtual bool _do_equivalent(const status_code<void> &code1, const status_code<void> &code2) const noexcept override  // NOLINT
     {
       assert(code1.domain() == *this);
       const auto &c1 = static_cast<const _mycode &>(code1);  // NOLINT
-      return typename StatusCode::domain_type()._do_equivalent(c1.value()->sc, code2);
+      typename StatusCode::domain_type foreignDomain{};
+      return static_cast<status_code_domain &>(foreignDomain)._do_equivalent(c1.value()->sc, code2);
     }
     virtual generic_code _generic_code(const status_code<void> &code) const noexcept override  // NOLINT
     {
       assert(code.domain() == *this);

```
I've put a minimal demonstrator on [godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGE6a4AMngMmAByPgBGmMQgZgDspAAOqAqETgwe3r7%2ByanpAsGhESzRsQm2mPaOAkIETMQEWT5%2BUpXVGXUNBEXhUTFxiQr1jc05bcPdvSVlgwCUtqhexMjsHCYaAILIBgoKANSRG5sm8VZb%2B5f7VMR4rvs7THv7eCYAzOcnW0nEqASYDkw6BAxyu%2BwAbnhGl4xBDUHh0PsAO4kADWEDm%2B3eABF9hp3p9jqdsQSiVtHs9ESB9kkvJFaHhkIciWdjj8/gD/sDQVdwfDESjiOjMahwTFblgeZdTp8wcSWSSPmTtrsDnh9tTafTGcytjK2XSGcgQRdefyXgw%2BajMBipVjWaawdKzG88FR9kI7WDEeDSY6nZNHMgAPqiYbvNyRLFmABs72wEHBcwAdILhX7Nk6ruY3lUlF6rugMam0balf65S7XG67fK9d9fv9Adz/XyEcjSyKxcQJZhaw7M9n4iS9cOM8cQgR9iwmCFbaPZVc8MWQlabXNx2OthwFrROABWXh%2BDhaUioThuazWfYKJYrTDRt48UgETQ7haokBveLJjRvACcZgaDGZhcDG/7xPE/4xvonCSEeb5npwvAKCAGgvm%2BCxwLASBoCwSR0DE5CUHhBH0LEwBcE%2BpBYJCqwAGp3EiADySSMJwz40LQ/zEKhECRIhkQhA0ACeHG8EJzDECJzGRNonLiaQeFsIIzEMLQYknrwWCRF4wBuGItCodw2mYDORjiFpNFQpyeBisZp6YKoAJeP8imTlUiEMpExCiR4WCIQQtwsOJCxUAYwAKIxmAsWxx6cbIIhiOwbT8IIigqOoVm6Fw%2BiGMYV6WPoeCRKhsDMGwICRKgqQEKQ3YcQAHGYO6kBAFXsFQLB1Q13AaP175nkkNQMMZAC0wzoDipiWNYQH7GNzFmAt2Kem82LPqK4oIpgZUYu0tnOBArhjK0pBBCEfSlAMuUpGkI2nXod0FAw0z9LEuV2IdDBdKMngtHoX0OJ0Iw9JdMw3bYoOPZ9oNvddH0LLeyyrBIu4HghVnnhw%2ByqI1MZjTGkj7MAyBMlRyZcPsEC4IQJCPlwcy8K%2BWlzB%2BX5mJTkhvG8RNvM18QaNz0h7hw8GkMep7YyhaEYazbUwIgKCoPhhFkBQECkWrKAGEYYH9TRmB0Zg0WxexJl8HQPF8QJVmSaJin29JsnyQ4inKYwBBqRpiE6XpBm0EZilYOZwCWae%2BDELZ9mIU5LluRbHmi6e3m%2BdJ/lrKeQV4CFJlhRFUVMax5sJYISXiKlsgZWoiG6GYeVGCghU2N5e3taw7DVbV9UDNwzWte3lVdT1AxBV4DComzQ0jeNk3Tc382LctY2rTim3dr2e1I1U30uAw7j/eM537/Dsy3fkD2H2dz0jafkNAyNv1NFfgM78DtRw%2BD72A9DL%2Bw1MX8EZo0WCjFK6MOCHglohbGuN8aE2Jo8Iw%2BwwK/l/NTWmRBiAMyZnLLQU9PxvA0MmRqXB4iSDMP%2BSQ/UnyQXrqLcWkteDS1sLLFmeDwEtSgVjZCuDBrdjSM4SQQA)

**Comment by ned14** [comment]
@BurningEnlightenment beat me to writing that comment. Thanks!

Is this issue now fully addressed?

**Comment by cstratopoulos** [comment]
Yeah thanks both of you!

**Comment by ned14** [comment]
Thanks for reporting it!

**Comment by BurningEnlightenment** [comment]
No, derived domains still need to explicitly befriend the `detail::indirecting_domain<>` as demonstraded [here on godbolt] (you can toggle the `DO_REPRO` definition). This is expected as we still need to apply the fix I posted above to every wrapped `status_code_domain` method.

I wanted to submit a PR, but didn't get to it ☹️ 

[here on godbolt]: https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGE6a4AMngMmAByPgBGmMQgAMwAHKQADqgKhE4MHt6%2B/ilpGQLBoREs0bGJtpj2jgJCBEzEBNk%2BfgBsVTWZ9Y0ExeFRMfFJCg1NLbkdo739peXDAJS2qF7EyOwcJhoAguZxIcjeWADUJnFuCAQEyQogAPR3xEwA7gB0wIQIXpFeSmuyjAIrzQLDuoXQUju0wIvwAtGgsHcWExRjEoSFgPRYQhMEwsMQoQBPVEsAD6MWIJDMrwQyWSZ2wW12OwexwAYnhVMd%2BMRjngFAovJhTmY4pIEscAJICoXHEHJOgY44CY6NFiwhgCTCw3GRPDHCChZ60PCRBbHZ6fY4AcTCcmOmFUBEY6QECmVVCoTL2eCoWCox1JpO2ymUgWwQe9ooOR2FZzcyFGxAxDKjcWqvuOYDA/pCmHQEFJAFkhG5SQA1bAAJQWTOYbAUySY62OLEJIBAWAadG9AHYrDtjsd65hG83hUwAG6oPDoUlJjGkmNeLBMocmftpzO58GF0nWwKSixl0nm8xtc9ZnOYGi7oNyNyH49B2uDofHVkAFQQ/OOxEwMLEAw7ohAQ3IkMOAiwpiprIMcSYUiQpJkMcPxgTBkTIGAHAge6TZNHgyBeAYxC0ISFqYHgxDoPBqAUX%2BAFMCEfIEGu76Os6QEimYbjmGYcoII0xwAFQIcQlLEMhECgQ64kMD4pACUJwk/FQinpAAXpgpJgap9AMLWcQDrsorVEobFDhxMQMNxvFmPxMliRJUkyRS8ksIpyCCbyKleGp8F4FpOmoX5%2BmGcZeyuL6bEbgAIkOrIjmOLZTjOc4LkYS4MIcK6YH28Ufncw6sKOTYtl2TG0GmUVejsdYlclwptn2xlJWVwpKPxZzxUIACaQiftgRaktWVYAPJVmYpJhNsRbYEIyjbG4jJGd6OyHCi7qkqk6SqKSCLaegqDIiEZzGQ82bHNsxzKGNQiSgAGrJElyhgmCKQQCBpMK/6AeCqHkSYbQaG5qBAxorxMr8So7Zy%2B1vaccTxZ1HbQr88Oruc20FHtB2kkdJ0MKmq0sncl3XY2mDIHgYj8kwtQ2agAbg2jCjkuJJDg%2BBvKfcKt33U9iG8gdxwE0xDCQzs0NGMcsN7ULiPI5gZiow0MJs0L8bY7tGOHcd4vExFLLCZd37CngLDJPQbCCPTmQescvOi/rzE8jdd2Pc9EEHQoH1fUoDF/fmAOnMDoPg5L13CXcTIbQKgZy7r%2BMuzZICy98JpwSjICs0nYunXVm5vs6lsGM6iMJgY8exSnn6EskeVxNg3LJq4cpV%2B62e5wdZ1rSZ%2BwBtmsVjaSVbYMo41sSXVv03G5xx%2B6PTqx4WCeR3V20LQqCiEQxAMi3eBtwv8HKx2FV0B2IT4P%2BDiLvnRMk/3NV90O0vAIGkQonPSsqznavo3je%2Bvc6pvmhIRD%2BX9VbJkyv%2BAMpJkQAGttIZWAMhG80lBBynNJqR06xkisTfBuYy74lK8lUlQGIJgACsFguAaDMJIah8VurcT4sA/uvp/SBgAOqSjCHEMwFl4IEH/BzSSCgIDkJiOpQKmAmaSL8hQ4gSwsHsMiiaAMO58x7gPEeE8Z4zAXkMVeLRBZ7yPj0S%2BBKRVBIMHQPQY4GEsI4QolRGiTkkLEAgK%2Ba674vLKXdCw8%2BtAOypVnPOERi5lxYCgULKSyBFJSJQppORVAFGehiAscK1jjhhDGoeMIn4hG%2BggO6bMLD5Kb3wcooRRChFDiTNlZIhJ0lKPUjIrS8iknmlhMcLg2TCq5PyXwopb4SFJOobQ%2BhcQmGK2OBodhJC4rVQ0SYm8eYzHBlDOGF8QjgmhOnOElBWUcoxL/qI5yXiEkhQyck2RXTFGZPCis8yYzhEXM8RAa5SSOmpNaU8tRpk7HRTeSk4K%2BlgCfTmUmfS/yalGRIYipFSLWR5IKaM3xQ4mBeCICJZI0K1aEX2iiVi89vIiQZBAZEm9t4QAhVC6wfSslnRyWikZxS0n4u6hU4itBqk%2BKWUXTF75fqrBsqST%2BSgoGLlgRAPiVBKrB1xcAACrZRwKCYCqlux14LEhLnxZ5bzllvLYCwZAzSIDJESY8lC9KEAigsEyllgy2WFKEaKriErIEgHpsdIlsC0BeEEPmCJ0DUGyqtccO1hrfHGuZNsZIGdCIgDYhdMAxwzbHEnGIWUBB67CiZo7HE7sBavVXhaH8Xk%2BTukMKHDQoFwZsTflmnN2k80NzmQ2x%2Br90gyy9VK85MqbxqLfGm44sUbzYtoGBNAwERFeAcJzN8s7USqGSLyR0VtCKEATjjPOKcIDtsYCVCBA6g14AAI5CiXHOI9fIaIsI0KoJgVCACcL62gUKoVQOIdDX1xDiNg1AuDMD4PqccNO/bMDSXQAK04Qr1y9limxbWcNAEHpXWBVDuM3rJ0JiKNoZ4kai0ncRUlxDd063Q4TQsidqPiwI%2BeIj8V/RTvIyhujuH74EdQA3J4u9upfLdFhzjWA8MMaY3M1jZHFmUbQ1xlOPG%2BO%2Br3kjWje76PMXPJJoJpHp2yYAH7Yf3TR5jJGFUycfqmsm6aPBzs3byXtmIAIqhVVcGIrxjhVgAmK90mGHOyw0wp/D2bkxMEiPQSODTCVwRCCaUIr17NruFsJuTOGxPcfPG57xI7fGTiojCMQ7yh0BhHN4xLoxIIgfwcqScFJZxxn7IHMVxWYHoL4nLZ2hMDUsriqy4ZbqQF5YK14IrTZCRbzxFlfgwVxuTbnCEfg5XMNVdUHgsCqA6viQazFBDIqfNcSISk%2BR2bvBtvzSo47aTu7BYY8JAxjqrsQFO9eo9SxwNIogLTYAmo0kvfOw3Ijzdvu/dKf/NmmmbL3aI2yVUJofsndbTpC7EG4d4AR9d8HJm7u1iQ7JuNTJ12oGdA4fMKa3z5aaKN2gqFUCeEDEdUkCq6CrGgytruWOe7nEOegfe54DrmhWzgtboGNtbeTCcZFUvpcy/fKigbGLEMUaxQKGIBAhNYFePfcr3LiPCU%2BvyAZsvjcm9N2b83LqFfuoOzZMByBiWjHjCt0TcZDGUoF68f75XynEYWQii3AfA/9fRbt5DFORtFciHTmnydyRXrwKdwEQm50n1/jdzGbged88MQdLgnlUsc/pgAt68Ys9NwIwdMwgvUvC/W7V%2Brkv5ch8IXtlXfx1e561we5jLD9c/gUEboPQ/h8W6b%2Byt5K3sW4v51wAldt7eiEd/PVLLvGNNw15gfpzqR875l2PwbwqSmV676ZxWveDcD9qa3vxqWp90X511YjduHekoTCvoLJxtPr8rwM/fivEUeo2TIBcCe6to65IwsLIDUhe4xqCph6H5pLH7a495P6nwgAqqhDJgL63YhBwZK7gaT44r3456P7IwxYv5O4F5oEYExBEoixf7YAb5V7Op/7gYlLP6L6v5dqMFQGgFnbeIoHxTAF8FCgCHgZ1JvIkKAGOzEBCiyZwFX7wFSE27chiDmTdrwZKFZoR407Zw0FYG6yBj6F0FvTJ6VaF7qy6yl5pTZ5tAC4VZgS16i717baN5FSur/4SHCqbRq4b4n7izgHIZ64X6D675hFy7uFW4T635EEV5z6OAL4kqUEp6r4MEb6hHhERFDLN7CrSF6GMC0HYFYBg7z4UHnDZwUimDf4iHQZZKwGaFsSU6Fa6GRJtZwKM4NgaoqpmFgQWHF4Z5l7Nz85vTV4p5OE1abYN7CiW45H4FvI%2BFNB%2BHIFn7BH94ZGZFB6sHREp535xEsIcFJHL4pEf6u4Xjf4jHb6ZFbG5EqHwJMBIKholZfI1FiEaEE7RiaLrJ3huChhyBhC8JhCxRni9i8QgnmYbJ7jYAPTLTKCfiShjRhBCDAmgluDgm7gDTbCAnbBVixTzQRiShCCkh8KkifgAASEYpJY0cgQg2AcGfUA0Q0I0VY40k000E02An4cgVYYQ2hVORWPODOqAOkCAlIzw5IIu%2BCmQPRqeqsReEOJe3ONh5ewxWAoxlWkxrh0x1xcx3hquixB0/hIQgR5%2BaxlxGx5pyK2pN%2BOxsR/O8RdBhxb%2BxxVGCMaRAuZpFpsuVpQ4n0opMpf8cp7MEkWsLu4mp03%2B9R7x6YwKtUuweOVmpM5MDhAWCgKwawwooWNMEWwobsTs/MnsIs98ikzwla9qv4n09MDs4M4cwMnm3mQcNEkQgMwMxmkOHY2WtYtZscwmAWrZOBNkoZQCj8cWeYyZyWDhaW2OWmhifZGWKc7ZAEOWhcFG0hg5KcaieOQ2BOOwMkpmLUQibYHYq%2BgokQ2gVMrE/YCy8ZyurY7YOcaBiC2koQqI6UnOphJ5Z5DgMacaHASwISHAVCvAfgHAWgpAqAnAdkVglgtEqwLYewPApABAmgv5SwCCIAVCIBGgCQvYr6bQ4oVCZgGgwMCQUg%2BgnAkgQFyFYFnAvAtwGgiFyFSwcAsAMAiAKAx0Co9AZAFAQmlsdAQwwAXAv6pAWA%2BW6w5Yh8zwY0DcwFCFNA06MQtwkiVFeozAxA7Y3AvAqljQhIY0p555nACFIINsBAY0DAZEVFWAPwwAbgYgtAtwmlIlmAyIRg4gIFvA1855Ceo4VFjoVMOKGwCFoE1QVFJokQTw6lK8GwoFkSLAhlv5fABgwACgElmAUlMl8VMgggIgYg7ApF/AggigKg6g7lpAugeeBgRgKA1g1g%2BgpotwsAI4IAUeaQBApAW2hlCQZgCVhoJUIAVALAbVHV3AGgo1KFYFkpbonAsIowvOSMpglg1ghFxwsIY0/EsIsUw8o848k8SMCFGpEuPlkASwdgXlzgEArgEwfgeeQQeYcwQweesMDMV1egT1mQswgwsQeep1t8dQYwzQngrQegP1DMPQTQH1ZQD1tg/1L131/1EN8w/SywsFeVf5nAgFpAwFoF4FHAxwqgCQbQsIeFjiyAcEQlrws%2BEAuAhAEE8FCwvASF7lTFSA8o/F3FlArNXFKAlVglwM9FolhEmAqV6VjAmV8lnESlkQKlIQOlmV2l6leln5jNRlx0JlZlFlpVVlXgNldlDlCFWALlzmllVEXldWDloFflREzomVwV/5oFYVEVhIUVVFsV8VSwVASVKVkl0lotjlBVwgog4g%2BVsgRVagVFugZg%2BghgxgNVlgdVkQDVUATVLVow7VQw3AXVPVTVA1Q1Qw86DACCWSE1DMDlM1BAc1sUC1UFFgy1q161m1I8Y8E8Y03U%2B14uDWidJ11QZ1fgF1disNpAt1JQn1r1BQz1gNuQj1Y971d1I9313dv1DAYNANOQ11nQPdy9CNUN0w4wE9a9O9fQs9kNX1J1aZ6wEgaNAFlFpVONeNBNRNkg7c0dfSbQrwEMGgBo1Nu8Iov69NDFTNqFIA4orwr6XAhFcQGFkgOFcQr6ZgFV5FvAcVcQvYrwkgAGaDr6XVuFGgb6HQWNvAONtFIA9FjNWgTFrFEASAKw1wOK5AHNHFbNYQfVHA%2BNhNxNwApNfScQFNvA%2BYNNEueg/tOVQd0g/todJVoF5VpAzwTwyQbtZFV9mNVFONY0OKiaG2AYrDD9JNZN3DlNHgfFXFP9/SDNjFpAlDIA1D6jdDvFnFMQTDbAnAWjxNG0MsXAr979vD%2BAu8s4gjsgwjeVojIdSgYdpVEd0jsj8j/5GN%2BD1FHAqjNDGjd9bDj9rj787jb9b9BoBjdjvIewVepjADpAOIeIQw3iCjFFpAcVbQ1IVCbQbQdTGgXAvYGgMDkgGg0gsThDtgxD/9ZDgDwDoD4DkD0DsD8DHAcQ192NNFfT41/53VSjN9MzpD41W2rofgkgQAA%3D
