### ISSUE TITLE
std_error_code not included in the single header implementation?

### ISSUE THREAD

**Issue by zomgrolf** [ned14/status-code#6]
Have I missed something? Is that deliberate? Looking at the single-header implementation, there's no mention of std_error_code?

Also, minor thing, but the paragraph on the front page of the repo, that describes how to fetch the single-header version is incorrect (it points to the non-existent develop branch).

**Comment by ned14** [comment]
Yeah, what headers include which others is poorly documented. The single header file is `system_error2.h`, and only includes what it includes. Which, amongst others, is not `std_error_code`. I'll improve the docs on this. Thanks for the report.

**Comment by ned14** [comment]
Fixed (see Readme in single-header)
