### ISSUE TITLE
`<cstring>` content gets potentially dragged into the `system_error2` namespace on APPLE

### ISSUE THREAD

**Issue by BurningEnlightenment** [ned14/status-code#61]
https://github.com/ned14/status-code/blob/4f5f18c4f437ba5f17aac300875a12b2b8d661fc/include/status-code/posix_code.hpp#L36-L42

**Comment by ned14** [comment]
Heh. That probably never was noticed due to `extern "C"`. You want to fix it?

**Comment by BurningEnlightenment** [comment]
oh, the fix is even more trivial than I thought:
https://github.com/ned14/status-code/blob/4f5f18c4f437ba5f17aac300875a12b2b8d661fc/include/status-code/posix_code.hpp#L34-L42
I will submit a PR right away.

**Comment by ned14** [comment]
So you can't remove the `<cstring>` include on Apple, else stuff breaks. It was introduced only due to some other issue opened here. You've just undone that issue fix :)

I'd just move the include outside the system error 2 namespace.

**Comment by BurningEnlightenment** [comment]
But it is included unconditionally 5 lines prior?

**Comment by BurningEnlightenment** [comment]
@ned14 So now I'm mightily confused. Do we try to avoid including `<cstring>` in `posix_code.hpp` on Linux? Is the unconditional `<cstring>` include an oversight?

**Comment by ned14** [comment]
I missed that.

Including `<cstring>` the second time will be a noop because it's already been included.

Sorry about the noise.

**Comment by BurningEnlightenment** [comment]
Don't worry, I didn't notice it at first glance either 😄
